apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/nmukherj-tenant/devfile-sample/devfile-sample@sha256:8543caf5ecefbeac237a4fba2c4c59230a566b899ab0224b3b50289d98140478
        name: my-nodejs
        resources: {}
status: {}
